In [7]:
import pandas as pd
import os

In [8]:
CATALOGUE_PATHS = {
    "A": "../data/raw/catalogue/jwst_bubble_properties_A.txt",
    "B": "../data/raw/catalogue/jwst_bubble_properties_B_fixed.txt",
    "C": "../data/raw/catalogue/jwst_bubble_properties_C.txt",
}

OUTPUT_PATH = "../data/processed/metadata"

os.makedirs(OUTPUT_PATH, exist_ok=True)

In [9]:
all_catalogues = []

for catalogue_label, path in CATALOGUE_PATHS.items():
    df = pd.read_csv(path)
    df["CATALOGUE"] = catalogue_label
    all_catalogues.append(df)

df_all = pd.concat(all_catalogues, ignore_index=True)

# Creating a global unique ID
df_all.insert(0, "GLOBAL_ID", range(1, len(df_all) + 1))

df_all.head()

,GLOBAL_ID,ID,RA_DMS,DEC_DMS,SEMI_MAJ_PC,SEMI_MIN_PC,AVG_RAD_PC,PA_DEG,ARM,DIST_ARM_PC,GAL_RAD_KPC,CATALOGUE
0,1,1,24d08m55.9s,15d48m7.9s,86,86,86,0,3,145,5.22,A
1,2,2,24d08m56.7s,15d48m2.9s,24,24,24,0,3,127,5.05,A
2,3,3,24d08m57.0s,15d48m9.0s,42,42,42,0,3,138,5.21,A
3,4,4,24d08m58.0s,15d47m44.9s,25,25,25,0,3,101,4.54,A
4,5,5,24d08m58.2s,15d48m2.6s,24,24,24,0,3,114,4.98,A

In [10]:
# df_reduced = df_all.drop('ARM', axis=1)

df_reduced = df_all.drop(['ARM', 'DIST_ARM_PC', 'GAL_RAD_KPC'], axis=1)

df_reduced.head()

,GLOBAL_ID,ID,RA_DMS,DEC_DMS,SEMI_MAJ_PC,SEMI_MIN_PC,AVG_RAD_PC,PA_DEG,CATALOGUE
0,1,1,24d08m55.9s,15d48m7.9s,86,86,86,0,A
1,2,2,24d08m56.7s,15d48m2.9s,24,24,24,0,A
2,3,3,24d08m57.0s,15d48m9.0s,42,42,42,0,A
3,4,4,24d08m58.0s,15d47m44.9s,25,25,25,0,A
4,5,5,24d08m58.2s,15d48m2.6s,24,24,24,0,A

In [11]:
print("Total bubbles in mergedCatalogue.txt:", len(df_reduced))
df_reduced.head()

Total bubbles in mergedCatalogue.txt: 3318

,GLOBAL_ID,ID,RA_DMS,DEC_DMS,SEMI_MAJ_PC,SEMI_MIN_PC,AVG_RAD_PC,PA_DEG,CATALOGUE
0,1,1,24d08m55.9s,15d48m7.9s,86,86,86,0,A
1,2,2,24d08m56.7s,15d48m2.9s,24,24,24,0,A
2,3,3,24d08m57.0s,15d48m9.0s,42,42,42,0,A
3,4,4,24d08m58.0s,15d47m44.9s,25,25,25,0,A
4,5,5,24d08m58.2s,15d48m2.6s,24,24,24,0,A

In [12]:
merged_output_path = os.path.join(OUTPUT_PATH, "mergedCatalogue.txt")

df_all.to_csv(merged_output_path, index=False)

print("Saved full collective catalogue to", merged_output_path)

Saved full collective catalogue to ../data/processed/metadata/mergedCatalogue.txt